groups:
- name: nginx_alerts
  rules:
  - alert: NginxDown
    expr: nginx_up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Nginx is down!"
      description: "Nginx on {{ $labels.instance }} is not responding."
