global:
  scrape_interval: 15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - "alertmanager:9093"
rule_files:
- "/etc/prometheus/alert.rules.yml"
scrape_configs:
- job_name: 'node_exporter'
  static_configs:
  - targets: [ "18.212.171.4:9100" ]
- job_name: "prometheus"
  static_configs:
  - targets: [ "localhost:9090" ]
- job_name: 'nginx'

  static_configs:
  - targets: [ '18.212.171.4:9113' ]