pipeline {
    agent any
    environment {
        PROJECT = "self-healer"
        AWS_REGION = "us-east-1"
        AWS_ACCOUNT_ID = "551796573889"
    }

    stages {
        stage('Output Environment Variables') {
            steps {
                script {
                    env.TF_VAR_project_name = "${PROJECT}"
                    env.TF_VAR_aws_region = "${AWS_REGION}"
                    env.TF_VAR_aws_account_id = "${AWS_ACCOUNT_ID}"
                    echo "Project Name: ${env.TF_VAR_project_name}"
                    echo "AWS Region: ${env.TF_VAR_aws_region}"
                    echo "AWS Account ID: ${env.TF_VAR_aws_account_id}"
                }
                sh 'echo "Environment Variables Set."'
            }
        }

        stage('Initialize Terraform') {
            steps {
                script {
                    sh 'terraform -chdir=deploy init'
                    sh 'terraform -chdir=deploy plan -out=plan.tfplan'
                }
            }
        }

        stage('Apply Terraform Infrastructure') {
            steps {
                script {
                    sh 'terraform -chdir=deploy plan -out=plan.tfplan'
                    
                }
            }
        }

        stage('Deploy Instances') {
            steps {
                script {
                    sh 'terraform -chdir=deploy apply plan.tfplan'
                    sh 'terraform -chdir=deploy refresh'
                    env.ANSIBLE_IP = sh(script: 'terraform -chdir=deploy output -raw ansible_ip', returnStdout: true).trim()
                    env.PROMETHEUS_IP = sh(script: 'terraform -chdir=deploy output -raw prometheus_ip', returnStdout: true).trim()
                    env.NGINX_IP = sh(script: 'terraform output -chdir=deploy -raw nginx_ip', returnStdout: true).trim()
                }
            }
        }

        stage('Build Servers') {
            steps {
                script {
                    dir('deploy') {
                        sh '''
                            echo "Ansible IP: ${ANSIBLE_IP}"
                            echo "Prometheus IP: ${PROMETHEUS_IP}"
                            echo "NGINX IP: ${NGINX_IP}"
                            chmod +x deploy.sh
                            ./deploy.sh
                        '''
                    }
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}